spring:
  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: false
    mode: LELEGACYHTML5
    servlet:
      content-type: text/html
  redis:
    host: localhost
    port: 6379
    timeout: 2000
