spring:
  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: false
    mode: LELEGACYHTML5
    servlet:
      content-type: text/html
  redis:
    host: 192.168.0.8
    port: 6379
    timeout: 2000
